Updated Socket
eyedea-io/syncano-socket-markdown-converter pull request #1
Opened 2018-11-06 09:44 UTC by olapinska

2018-11-06 09:48 UTC, ksyhoo approved these changes

2018-11-06 10:40 UTC, mkucharz requested changes

2018-11-06 10:40 UTC, mkucharz commented on test/__mocks__/fb.js
> +import fb from 'fb'
Remove this file is a FB mock, it is in boilerplate as an example.

2018-11-06 10:40 UTC, mkucharz commented on socket.yml
> +   input:
We have `inputs` and `outputs`.

2018-11-06 10:40 UTC, mkucharz commented on test/__mocks__/axios.js
> +import axios from 'axios'
We are not using axios, so we don't need mock also.

2018-11-06 13:07 UTC, Idered requested changes

2018-11-06 13:07 UTC, Idered commented on package.json
> +    "@syncano/cli": "0.13.0-alpha.f6ea95d4"
This should be:

```
"@syncano/cli": "^0.13.0-alpha.f6ea95d4"
```

Which means version `0.13.0-alpha.f6ea95d4` or higher `^`

2018-11-06 13:07 UTC, Idered commented on socket.yml
> +          “message”: “Conversion failed!”
Invalid quotation marks `“` should be `"`

2018-11-09 20:30 UTC, mkucharz requested changes

2018-11-09 20:30 UTC, mkucharz commented on socket.yml
>  description: Simple Markdown do HTML converter
Obsolete  description and version. Move keywords to `package.json`.

2018-11-09 20:30 UTC, mkucharz commented on src/convert.ts
> +
Remove empty line.

2018-11-13 14:16 UTC, jonny22094 approved these changes

2018-11-13 14:16 UTC, merged